### PR TITLE
Updated the "Feature Count" and renamed it as "Frequency". 

### PR DESCRIPTION
**Pull request by ghubrakesh**
issue #270.

### CODE REVIEW

**Comment by ebolyen** [comment]
Thanks @ghubrakesh! There's some test failures, but we can help with that.

**Comment by lizgehret** [comment]
Hey @colinvwood @Keegan-Evans could y'all get this one wrapped up before Weds?

**Comment by colinvwood** [comment]
Hey @ghubrakesh we fixed the failing tests, if you merge our pull request in your repo (https://github.com/ghubrakesh/q2-feature-table/pull/2) we should then be able to merge it here! We're actively working on a release right now and we would love to include your contribution. If you can get this done today it'll go in this release, otherwise it'll probably go in the next one. Thanks!

**Review by ebolyen — APPROVED** [review]
Thanks @ghubrakesh (and @colinvwood)!

**Pull request merged**
