### PR TITLE
HACK: Remove vega editor for now

### LINKED ISSUE #229: Upgrade Summarize Plots to Vega 5
**Improvement Description**
Somewhere along the line updates to vega broke our vega visualizations. This includes summarize plots. For now it looks like we're going to remove the ability to open them in the vega editor as a band aid, but at some point we'll need to update the plot to work properly with the updated editor.

### PR DESCRIPTION
**Pull request by Oddant1**
A temporary band aid for #229

### CODE REVIEW

**Comment by Oddant1** [comment]
Oh what the heck I thought I did

**Comment by thermokarst** [comment]
Oh weird - maybe my page was cached? I just reloaded and its gone - sorry about that!

**Comment by Oddant1** [comment]
> maybe my page was cached?
That darn internet trolling us as usual

**Comment by thermokarst** [comment]
Travis is failing due to unrelated whitespace issues - can you please cut a new PR that fixes that? Thanks!

**Comment by Oddant1** [comment]
> Travis is failing due to unrelated whitespace issues - can you please cut a new PR that fixes that? Thanks!

Can do

**Pull request merged**
